const play_button = document.getElementById("Play")
// const easy_button = document.getElementById("Easy")
// const medium_button = document.getElementById("Medium")
// const hard_button = document.getElementById("Hard")

// inc_button.addEventListener('click', incCount)
// inc_button.addEventListener('mouseover', revColI)
// inc_button.addEventListener('mouseout', retColI)
// dec_button.addEventListener('click', decCount)
// dec_button.addEventListener('mouseover', revColD)
// dec_button.addEventListener('mouseout', retColD)